# Generated by Django 4.1.3 on 2022-11-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivos',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='dispositivos',
            name='data_rev',
            field=models.DateField(verbose_name='Data de Revisão'),
        ),
        migrations.AlterField(
            model_name='dispositivos',
            name='image',
            field=models.ImageField(upload_to='dispositivos', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='dispositivos',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Descrição'),
        ),
    ]
