# Generated by Django 4.1.3 on 2022-11-11 03:51

import dispositivos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_alter_dispositivos_code_alter_dispositivos_data_rev_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivos',
            name='image',
            field=models.ImageField(default='default/no_image.jpg', max_length=255, upload_to=dispositivos.models.Dispositivos.image_upload_to, verbose_name='Imagem'),
        ),
    ]
