# Generated by Django 4.1.3 on 2022-11-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0003_alter_dispositivos_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivos',
            name='maquina',
            field=models.CharField(default='Padrão', max_length=50, verbose_name='Máquina'),
        ),
    ]
