# Generated by Django 4.1.3 on 2022-11-12 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0004_dispositivos_maquina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('operador', models.CharField(max_length=50, verbose_name='Matricula')),
                ('defeito', models.CharField(max_length=250, verbose_name='Descrição do Defeito')),
                ('data_entrada', models.DateField(verbose_name='Data da Solicitação')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.dispositivos', verbose_name='Dispositivo')),
            ],
        ),
    ]
